// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: advice_with_patient.sql

package db

import (
	"context"

	"github.com/gofrs/uuid"
)

const createAdviceWithPatient = `-- name: CreateAdviceWithPatient :exec

INSERT INTO
    advice_with_patient (advice_id, patient_uuid)
VALUES (?, ?)
`

type CreateAdviceWithPatientParams struct {
	AdviceID    int64
	PatientUuid uuid.UUID
}

func (q *Queries) CreateAdviceWithPatient(ctx context.Context, arg CreateAdviceWithPatientParams) error {
	_, err := q.db.ExecContext(ctx, createAdviceWithPatient, arg.AdviceID, arg.PatientUuid)
	return err
}
