// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: assignment.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
)

const createAssignment = `-- name: CreateAssignment :one

INSERT INTO
    assignments (
        title,
        description,
        patient_uuid,
        doctor_uuid,
        session_id,
        status
    )
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, title, description, patient_uuid, doctor_uuid, session_id, status, created_at, updated_at
`

type CreateAssignmentParams struct {
	Title       string
	Description string
	PatientUuid uuid.UUID
	DoctorUuid  uuid.UUID
	SessionID   int64
	Status      int64
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, createAssignment,
		arg.Title,
		arg.Description,
		arg.PatientUuid,
		arg.DoctorUuid,
		arg.SessionID,
		arg.Status,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PatientUuid,
		&i.DoctorUuid,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec

DELETE FROM assignments where id = ?
`

func (q *Queries) DeleteAssignment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAssignment, id)
	return err
}

const getAssignment = `-- name: GetAssignment :one

SELECT assignments.id, assignments.title, assignments.description, assignments.patient_uuid, assignments.doctor_uuid, assignments.session_id, assignments.status, assignments.created_at, assignments.updated_at FROM assignments WHERE id = ? LIMIT 1
`

func (q *Queries) GetAssignment(ctx context.Context, id int64) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, getAssignment, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PatientUuid,
		&i.DoctorUuid,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDoctorPatientAssignments = `-- name: ListDoctorPatientAssignments :many

SELECT
    assignments.id as assignment_id,
    assignments.title as assignment_title,
    assignments.description as assignment_description,
    assignments.status as assignment_status,
    assignments.patient_uuid as patient_uuid,
    sessions.id as session_id,
    sessions.date as session_date,
    doctors.uuid as doctor_uuid,
    doctors.name as doctor_name,
    doctors.description as doctor_description
FROM assignments
    JOIN doctors ON doctors.uuid = assignments.doctor_uuid
    JOIN sessions ON sessions.id = assignments.session_id
WHERE
    assignments.patient_uuid = ?
    AND assignments.doctor_uuid = ?
`

type ListDoctorPatientAssignmentsParams struct {
	PatientUuid uuid.UUID
	DoctorUuid  uuid.UUID
}

type ListDoctorPatientAssignmentsRow struct {
	AssignmentID          int64
	AssignmentTitle       string
	AssignmentDescription string
	AssignmentStatus      int64
	PatientUuid           uuid.UUID
	SessionID             int64
	SessionDate           time.Time
	DoctorUuid            uuid.UUID
	DoctorName            string
	DoctorDescription     string
}

func (q *Queries) ListDoctorPatientAssignments(ctx context.Context, arg ListDoctorPatientAssignmentsParams) ([]ListDoctorPatientAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDoctorPatientAssignments, arg.PatientUuid, arg.DoctorUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDoctorPatientAssignmentsRow
	for rows.Next() {
		var i ListDoctorPatientAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.AssignmentTitle,
			&i.AssignmentDescription,
			&i.AssignmentStatus,
			&i.PatientUuid,
			&i.SessionID,
			&i.SessionDate,
			&i.DoctorUuid,
			&i.DoctorName,
			&i.DoctorDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientAssignments = `-- name: ListPatientAssignments :many

SELECT
    assignments.id as assignment_id,
    assignments.title as assignment_title,
    assignments.description as assignment_description,
    assignments.status as assignment_status,
    assignments.patient_uuid as patient_uuid,
    sessions.id as session_id,
    sessions.date as session_date,
    doctors.uuid as doctor_uuid,
    doctors.name as doctor_name,
    doctors.description as doctor_description
FROM assignments
    JOIN doctors ON doctors.uuid = assignments.doctor_uuid
    JOIN sessions ON sessions.id = assignments.session_id
WHERE
    assignments.patient_uuid = ?
`

type ListPatientAssignmentsRow struct {
	AssignmentID          int64
	AssignmentTitle       string
	AssignmentDescription string
	AssignmentStatus      int64
	PatientUuid           uuid.UUID
	SessionID             int64
	SessionDate           time.Time
	DoctorUuid            uuid.UUID
	DoctorName            string
	DoctorDescription     string
}

func (q *Queries) ListPatientAssignments(ctx context.Context, patientUuid uuid.UUID) ([]ListPatientAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPatientAssignments, patientUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientAssignmentsRow
	for rows.Next() {
		var i ListPatientAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.AssignmentTitle,
			&i.AssignmentDescription,
			&i.AssignmentStatus,
			&i.PatientUuid,
			&i.SessionID,
			&i.SessionDate,
			&i.DoctorUuid,
			&i.DoctorName,
			&i.DoctorDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDoctorPatientAssignments = `-- name: ListPendingDoctorPatientAssignments :many

SELECT
    assignments.id as assignment_id,
    assignments.title as assignment_title,
    assignments.description as assignment_description,
    assignments.status as assignment_status,
    assignments.patient_uuid as patient_uuid,
    sessions.id as session_id,
    sessions.date as session_date,
    doctors.uuid as doctor_uuid,
    doctors.name as doctor_name,
    doctors.description as doctor_description
FROM assignments
    JOIN doctors ON doctors.uuid = assignments.doctor_uuid
    JOIN sessions ON sessions.id = assignments.session_id
WHERE
    assignments.patient_uuid = ?
    AND assignments.doctor_uuid = ?
    AND assignments.status = 0
`

type ListPendingDoctorPatientAssignmentsParams struct {
	PatientUuid uuid.UUID
	DoctorUuid  uuid.UUID
}

type ListPendingDoctorPatientAssignmentsRow struct {
	AssignmentID          int64
	AssignmentTitle       string
	AssignmentDescription string
	AssignmentStatus      int64
	PatientUuid           uuid.UUID
	SessionID             int64
	SessionDate           time.Time
	DoctorUuid            uuid.UUID
	DoctorName            string
	DoctorDescription     string
}

func (q *Queries) ListPendingDoctorPatientAssignments(ctx context.Context, arg ListPendingDoctorPatientAssignmentsParams) ([]ListPendingDoctorPatientAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDoctorPatientAssignments, arg.PatientUuid, arg.DoctorUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingDoctorPatientAssignmentsRow
	for rows.Next() {
		var i ListPendingDoctorPatientAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.AssignmentTitle,
			&i.AssignmentDescription,
			&i.AssignmentStatus,
			&i.PatientUuid,
			&i.SessionID,
			&i.SessionDate,
			&i.DoctorUuid,
			&i.DoctorName,
			&i.DoctorDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPatientAssignments = `-- name: ListPendingPatientAssignments :many

SELECT
    assignments.id as assignment_id,
    assignments.title as assignment_title,
    assignments.description as assignment_description,
    assignments.status as assignment_status,
    assignments.patient_uuid as patient_uuid,
    sessions.id as session_id,
    sessions.date as session_date,
    doctors.uuid as doctor_uuid,
    doctors.name as doctor_name,
    doctors.description as doctor_description
FROM assignments
    JOIN doctors ON doctors.uuid = assignments.doctor_uuid
    JOIN sessions ON sessions.id = assignments.session_id
WHERE
    assignments.patient_uuid = ?
    AND assignments.status = 0
`

type ListPendingPatientAssignmentsRow struct {
	AssignmentID          int64
	AssignmentTitle       string
	AssignmentDescription string
	AssignmentStatus      int64
	PatientUuid           uuid.UUID
	SessionID             int64
	SessionDate           time.Time
	DoctorUuid            uuid.UUID
	DoctorName            string
	DoctorDescription     string
}

func (q *Queries) ListPendingPatientAssignments(ctx context.Context, patientUuid uuid.UUID) ([]ListPendingPatientAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPatientAssignments, patientUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingPatientAssignmentsRow
	for rows.Next() {
		var i ListPendingPatientAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.AssignmentTitle,
			&i.AssignmentDescription,
			&i.AssignmentStatus,
			&i.PatientUuid,
			&i.SessionID,
			&i.SessionDate,
			&i.DoctorUuid,
			&i.DoctorName,
			&i.DoctorDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :one

UPDATE assignments
SET
    title = COALESCE(?1, title),
    description = COALESCE(
        ?2,
        description
    ),
    status = COALESCE(?3, status),
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?4 RETURNING id, title, description, patient_uuid, doctor_uuid, session_id, status, created_at, updated_at
`

type UpdateAssignmentParams struct {
	Title       sql.NullString
	Description sql.NullString
	Status      sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, updateAssignment,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PatientUuid,
		&i.DoctorUuid,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
