// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"github.com/gofrs/uuid"
)

type Doctor struct {
	Uuid           uuid.UUID
	Name           string
	PhoneNumber    string
	Description    string
	Crp            string
	PixKey         string
	PaymentDetails string
}

type Patient struct {
	Uuid        uuid.UUID
	Name        string
	PhoneNumber string
}

type PatientWithDoctor struct {
	ID          int64
	PatientUuid uuid.UUID
	DoctorUuid  uuid.UUID
}
