// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"

	"github.com/gofrs/uuid"
)

type Advice struct {
	ID         int64
	Message    string
	DoctorUuid uuid.UUID
	CreatedAt  time.Time
}

type AdviceWithPatient struct {
	ID          int64
	AdviceID    int64
	PatientUuid uuid.UUID
	CreatedAt   time.Time
}

type Assignment struct {
	ID          int64
	Title       string
	Description string
	PatientUuid uuid.UUID
	DoctorUuid  uuid.UUID
	SessionID   int64
	Status      int64
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type Doctor struct {
	Uuid           uuid.UUID
	Name           string
	PhoneNumber    string
	Description    string
	Crp            string
	PixKey         string
	PaymentDetails string
	CreatedAt      time.Time
	UpdatedAt      sql.NullTime
}

type Invite struct {
	ID          int64
	PhoneNumber string
	PatientUuid uuid.UUID
	DoctorUuid  uuid.UUID
	CreatedAt   time.Time
}

type Patient struct {
	Uuid        uuid.UUID
	Name        string
	PhoneNumber string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type PatientWithDoctor struct {
	PatientUuid uuid.UUID
	DoctorUuid  uuid.UUID
	CreatedAt   time.Time
}

type Schedule struct {
	ID         int64
	DoctorUuid uuid.UUID
	Date       time.Time
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
}

type Session struct {
	ID          int64
	PatientUuid uuid.UUID
	DoctorUuid  uuid.UUID
	Date        time.Time
	GroupIndex  int64
	Type        int64
	Status      int64
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}
